
name: Build and push the Docker image to ECR, Deploy it to the K8s

on:
  push:
    branches:
      - stagging

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: worldtradex

jobs:
  build-and-deploy:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push Image to Amazon ECR
        id: build-push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          SERVICE_NAME=$(basename $GITHUB_REPOSITORY)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_TAG=${BRANCH_NAME}-${SHORT_SHA}

          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${SERVICE_NAME}-${IMAGE_TAG} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${SERVICE_NAME}-${IMAGE_TAG}

          echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

